<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKGWskp0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKGWskp0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKGWskp0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKGWskp0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKGWskp0\App_KernelDevDebugContainer([
    'container.build_hash' => 'KGWskp0',
    'container.build_id' => '7106351d',
    'container.build_time' => 1664447174,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKGWskp0');
