<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGHMbbkW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGHMbbkW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGHMbbkW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGHMbbkW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGHMbbkW\App_KernelDevDebugContainer([
    'container.build_hash' => 'GHMbbkW',
    'container.build_id' => '6e7d3c57',
    'container.build_time' => 1664448183,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGHMbbkW');
